AllCops:
  TargetRubyVersion: 2.3
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - 'lib/**/*.rake'
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/CyclomaticComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

# This cop is designed to help upgrade to Ruby 3.0.
# It will add the comment `# frozen_string_literal: true` to the top of files to enable frozen string literals.
# Frozen string literals will be default in Ruby 3.0. The comment will be added below a shebang and encoding comment.
# The frozen string literal comment is only valid in Ruby 2.3+.
Style/FrozenStringLiteralComment:
  Enabled: false
