version: '3'
services:
  kraken:
    build: .
    command: bash
  kafka:
    image: ches/kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=127.0.0.1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - ZOOKEEPER_IP=zookeeper
    ports:
      - '7203:7203'
      - '9092:9092'
    volumes:
      - kafka_data:/data
      - kafka_logs:/logs
    depends_on:
      - zookeeper
  zookeeper:
    image: jplock/zookeeper:3.4.6
    ports:
      - '2181:2181'
volumes:
  kafka_data:
  kafka_logs:
